/**
 * PDF Report Generation
 *
 * Provides structured PDF report export for SIMVEX study dashboard.
 */

export interface ReportData {
  modelName: string;
  parts: { name: string; description?: string }[];
  notes?: string;
  generatedAt: Date;
}

/**
 * Generate a structured study report PDF (A4 portrait).
 *
 * Page 1: Header + model info + parts table
 * Page 2: Study notes (if provided)
 */
export async function generateReport(data: ReportData): Promise<string> {
  const { default: jsPDF } = await import("jspdf");

  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = 210;
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // --- Page 1: Header + Model Info + Parts Table ---

  // Header bar
  pdf.setFillColor(99, 102, 241); // primary/indigo
  pdf.rect(0, 0, pageWidth, 32, "F");

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(22);
  pdf.text("SIMVEX", margin, 16);
  pdf.setFontSize(11);
  pdf.text("Study Report", margin, 24);

  // Date (right-aligned in header)
  const dateStr = data.generatedAt.toLocaleDateString("ko-KR", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  pdf.setFontSize(10);
  pdf.text(dateStr, pageWidth - margin, 24, { align: "right" });

  // Model name
  pdf.setTextColor(30, 30, 30);
  pdf.setFontSize(18);
  pdf.text(data.modelName, margin, 50);

  // Divider
  pdf.setDrawColor(200, 200, 200);
  pdf.line(margin, 55, pageWidth - margin, 55);

  // Parts table
  let y = 65;

  pdf.setFontSize(14);
  pdf.setTextColor(60, 60, 60);
  pdf.text("Parts List", margin, y);
  y += 8;

  // Table header
  pdf.setFillColor(245, 245, 250);
  pdf.rect(margin, y, contentWidth, 8, "F");
  pdf.setFontSize(10);
  pdf.setTextColor(80, 80, 80);
  pdf.text("#", margin + 2, y + 6);
  pdf.text("Name", margin + 14, y + 6);
  pdf.text("Description", margin + 70, y + 6);
  y += 10;

  // Table rows
  pdf.setTextColor(40, 40, 40);
  pdf.setFontSize(9);

  for (let i = 0; i < data.parts.length; i++) {
    if (y > 270) {
      pdf.addPage();
      y = 20;
    }

    const part = data.parts[i];
    const rowH = 7;

    if (i % 2 === 0) {
      pdf.setFillColor(250, 250, 255);
      pdf.rect(margin, y - 4, contentWidth, rowH, "F");
    }

    pdf.text(String(i + 1), margin + 2, y);
    pdf.text(part.name || "-", margin + 14, y);

    const desc = part.description || "-";
    const descLines = pdf.splitTextToSize(desc, contentWidth - 70);
    pdf.text(descLines[0], margin + 70, y);

    y += rowH;
  }

  if (data.parts.length === 0) {
    pdf.setTextColor(150, 150, 150);
    pdf.text("No parts data available", margin + 2, y);
    y += 8;
  }

  // Summary
  y += 6;
  pdf.setDrawColor(200, 200, 200);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 8;
  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text(`Total parts: ${data.parts.length}`, margin, y);

  // --- Page 2: Notes (optional) ---
  if (data.notes) {
    pdf.addPage();

    pdf.setFontSize(14);
    pdf.setTextColor(60, 60, 60);
    pdf.text("Study Notes", margin, 20);

    pdf.setDrawColor(200, 200, 200);
    pdf.line(margin, 25, pageWidth - margin, 25);

    pdf.setFontSize(10);
    pdf.setTextColor(40, 40, 40);
    const noteLines = pdf.splitTextToSize(data.notes, contentWidth);
    pdf.text(noteLines, margin, 33);
  }

  // Footer on all pages
  const totalPages = pdf.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    pdf.setPage(p);
    pdf.setFontSize(8);
    pdf.setTextColor(180, 180, 180);
    pdf.text(
      `Generated by SIMVEX  |  Page ${p} / ${totalPages}`,
      pageWidth / 2,
      292,
      { align: "center" }
    );
  }

  // Save
  const safeName = data.modelName.replace(/[^a-zA-Z0-9-_]/g, "_");
  const dateTag = data.generatedAt.toISOString().split("T")[0];
  const filename = `simvex-report-${safeName}-${dateTag}.pdf`;
  pdf.save(filename);

  return filename;
}

/**
 * Legacy PDF export (canvas screenshot + optional notes).
 * Kept for backward compatibility.
 */
export async function generatePDF(notes?: string) {
  try {
    const { default: jsPDF } = await import("jspdf");
    const { default: html2canvas } = await import("html2canvas");

    // Capture canvas screenshot
    const canvas = document.querySelector("canvas");
    if (!canvas) throw new Error("Canvas not found");

    const screenshot = await html2canvas(canvas);
    const imgData = screenshot.toDataURL("image/png");

    // Create PDF
    const pdf = new jsPDF({
      orientation: "landscape",
      unit: "mm",
      format: "a4",
    });

    // Add title
    pdf.setFontSize(20);
    pdf.text("SIMVEX 학습 리포트", 15, 15);

    // Add screenshot
    pdf.addImage(imgData, "PNG", 15, 25, 270, 150);

    // Add notes if provided
    if (notes) {
      pdf.addPage();
      pdf.setFontSize(16);
      pdf.text("학습 노트:", 15, 15);
      pdf.setFontSize(12);

      const lines = pdf.splitTextToSize(notes, 270);
      pdf.text(lines, 15, 25);
    }

    // Save file
    const filename = `simvex-report-${new Date().toISOString().split("T")[0]}.pdf`;
    pdf.save(filename);

    return filename;
  } catch (error) {
    console.error("PDF generation failed:", error);
    throw error;
  }
}
